# Generated by Django 3.2.3 on 2021-05-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorID', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=500)),
                ('openingHours', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('KL', 'Kowloon'), ('HK', 'Hongkong'), ('IL', 'Island'), ('NT', 'New Territories')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(choices=[('PHY', 'Physio'), ('DEN', 'Dental'), ('CHN', 'Chinmed'), ('CLN', 'Clinic')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlistAPI.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('CNT', 'Cantonese'), ('MDR', 'Mandarin'), ('ENG', 'English')], max_length=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorlistAPI.doctor')),
            ],
        ),
    ]
