# Generated by Django 3.2.3 on 2021-05-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlistAPI', '0002_auto_20210517_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='district',
            new_name='language',
        ),
    ]
